### ISSUE TITLE
Error report - spigot1.12.2

### ISSUE THREAD

**Issue by momoservertw** [AddstarMC/BlockHunt#24]
The error happen after I finished  the setting of game area and restart sever.
It remove all the setting of Warps in "arenas.yml", and show lots of error report in console. (The following and battached file)
[Error_log_spiot1.12.2.log](https://github.com/AddstarMC/BlockHunt/files/1869129/Error_log_spiot1.12.2.log)
![image](https://user-images.githubusercontent.com/38014059/38210808-0809a1d2-36eb-11e8-91da-56e2571ee7f4.png)

Besides, players cannot move in the beginning of game.  (hiders, seekers)
[BlockHunt] Arena:test appears to have bad coords : pos1: NULL Pos2: NULL
[BlockHunt] Player has been returned to hiderswarp due to bad arena state

Spigot 1.12.2 (lastest version, 4/2)
Plugins:
ProtocolLib (v4.3.0 - https://www.spigotmc.org/resources/protocollib.1997/history)
LibsDisguises (development builds#199 - https://ci.md-5.net/job/LibsDisguises/lastStableBuild/)
BlockHunt (v0.3.0-ALPHA - https://jenkins.addstar.com.au/job/Blockhunt/lastSuccessfulBuild/artifact/target/)
-------------------------------------------------------------------------------------------------------------
**Error report in console:**
02:42:32] [Server thread/INFO]: [BlockHunt] Enabling BlockHunt v0.3.0-ALPHA-
[02:42:32] [Server thread/ERROR]: Could not call method 'public static nl.Steffion.BlockHunt.Serializables.LocationSerializable nl.Steffion.BlockHunt.Serializables.LocationSerializable.deserialize(java.util.Map)' of class nl.Steffion.BlockHunt.Serializables.LocationSerializable for deserialization
java.lang.NullPointerException: null
	at nl.Steffion.BlockHunt.Managers.ConfigManager.get(ConfigManager.java:151) ~[?:?]
	at nl.Steffion.BlockHunt.Managers.MessageManager$CType.NORMAL(MessageManager.java:168) ~[?:?]
	at nl.Steffion.BlockHunt.Managers.MessageManager.replaceColourVars(MessageManager.java:138) ~[?:?]
	at nl.Steffion.BlockHunt.Managers.MessageManager.replaceAll(MessageManager.java:116) ~[?:?]
	at nl.Steffion.BlockHunt.Managers.MessageManager.sendMessage(MessageManager.java:36) ~[?:?]
	at nl.Steffion.BlockHunt.Serializables.LocationSerializable.deserialize(LocationSerializable.java:56) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:519) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:519) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at nl.Steffion.BlockHunt.Managers.ConfigManager.load(ConfigManager.java:129) [BlockHunt-0.3.0-ALPHA.jar:?]
	at nl.Steffion.BlockHunt.Managers.ConfigManager.<init>(ConfigManager.java:45) [BlockHunt-0.3.0-ALPHA.jar:?]
	at nl.Steffion.BlockHunt.MemoryStorage.<clinit>(MemoryStorage.java:39) [BlockHunt-0.3.0-ALPHA.jar:?]
	at nl.Steffion.BlockHunt.ConfigC.<clinit>(ConfigC.java:18) [BlockHunt-0.3.0-ALPHA.jar:?]
	at nl.Steffion.BlockHunt.Managers.ConfigManager.setDefaults(ConfigManager.java:84) [BlockHunt-0.3.0-ALPHA.jar:?]
	at nl.Steffion.BlockHunt.Managers.ConfigManager.newFiles(ConfigManager.java:72) [BlockHunt-0.3.0-ALPHA.jar:?]
	at nl.Steffion.BlockHunt.BlockHunt.onEnable(BlockHunt.java:141) [BlockHunt-0.3.0-ALPHA.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[02:42:32] [Server thread/ERROR]: Could not call method 'public static nl.Steffion.BlockHunt.Serializables.LocationSerializable nl.Steffion.BlockHunt.Serializables.LocationSerializable.deserialize(java.util.Map)' of class nl.Steffion.BlockHunt.Serializables.LocationSerializable for deserialization

**Comment by CoolLord22** [comment]
Mine did this too. You have to recreate the arena with coordinates now (use /bh wand, then click the 2 corners and recreate the arena) so you may have to like remove the arena, and then re-make it.

**Comment by rt50631** [comment]
Fixed here:
https://github.com/rt50631/BlockHunt/commit/2a0b298c894f912a5e3e523b0dab687869f6fa2b
