### ISSUE TITLE
Issue with .replaceAll() in line 160 of class MesageM.java

### ISSUE THREAD

**Issue by XXLuigiMario** [AddstarMC/BlockHunt#8]
It throws a java.lang.IllegalArgumentException,
here's the stacktrace I get when using /blockhunt:

```
25.06 15:28:30 [Server] ERROR null
25.06 15:28:30 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'blockhunt' in plugin BlockHunt v${project.version}
25.06 15:28:30 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
25.06 15:28:30 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
25.06 15:28:30 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
25.06 15:28:30 [Server] INFO Caused by: java.lang.IllegalArgumentException: named capturing group is missing trailing '}'
25.06 15:28:30 [Server] INFO at java.util.regex.Matcher.appendReplacement(Matcher.java:841) ~[?:1.8.0_45]
25.06 15:28:30 [Server] INFO at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_45]
25.06 15:28:30 [Server] INFO at java.lang.String.replaceAll(String.java:2211) ~[?:1.8.0_45]
25.06 15:28:30 [Server] INFO at nl.Steffion.BlockHunt.Managers.MessageM.replaceVars(MessageM.java:160) ~[?:?]
25.06 15:28:30 [Server] INFO at nl.Steffion.BlockHunt.Managers.MessageM.replaceAll(MessageM.java:116) ~[?:?]
25.06 15:28:30 [Server] INFO at nl.Steffion.BlockHunt.Managers.MessageM.sendMessage(MessageM.java:38) ~[?:?]
25.06 15:28:30 [Server] INFO at nl.Steffion.BlockHunt.Commands.CMDinfo.exectue(CMDinfo.java:27) ~[?:?]
25.06 15:28:30 [Server] INFO at nl.Steffion.BlockHunt.BlockHunt.onCommand(BlockHunt.java:533) ~[?:?]
25.06 15:28:30 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-d2856ae-8f0f4ed]
25.06 15:28:30 [Server] INFO ... 15 more
```

**Comment by addstar** [comment]
It looks like your config or messages file has a syntax problem. Paste a link to your messages file.

Also, the "v${project.version}" tells me you have compiled this yourself and not using our builds from our jenkins server. Did you make any modifications to it?

**Comment by XXLuigiMario** [comment]
No, I didn't know there was a Jenkins repo, I'll try using that and I'll post back.

**Comment by CoolLord22** [comment]
This may sound dumb.. but where can I find the Jenkins repo xD

**Comment by Steffion** [comment]
I removed the Jenkins repo since this is no longer supported. You can build the jar by downloading the code .

**Comment by Narimm** [comment]
Actually we have a you can find it on our Jenkins @ https://jenkins.addstar.com.au/job/BlockHunt/

**Comment by CoolLord22** [comment]
oh awesome! I had tried cloning this build but it would always fail, i think maybe the repo was down or something? but its all good now! Thanks :D
